FROM debian:13-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      ca-certificates \
      iproute2 \
      iptables \
      wireguard-tools \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
